
// TODO Trim away the fat later
pub(crate) enum ConditionOp<Entity: OBBlanket> {
  All(Vec<Condition<Entity>>),
  Any(Vec<Condition<Entity>>),

  // IsNull,
  // NotNull,
  Contains(Vec<String>),
  Contain_Element(String),
  Starts_With(String),
  Ends_With(String),

  // TODO Actually type out all the concrete enum parameter types
  // TODO or use a macro
  // Gt(T),
  // GreaterOrEq(T),
  // Lt(T),
  // LessOrEq(T),
  // OneOf(T),
  // NotOneOf(T),

  // TODO remove after writing the macro to generate
  // Eq(T),
  // NotEq(T),

  // Between(T, T),

  // Test enums
  TestU8(u8),

  // start here
  Gt_U8(u8),
  GreaterOrEq_U8(u8),
  Lt_U8(u8),
  LessOrEq_U8(u8),
  OneOf_U8(u8),
  NotOneOf_U8(u8),
  Eq_U8(u8),
  NotEq_U8(u8),
  Between_U8(u8, u8),
  Gt_I8(i8),
  GreaterOrEq_I8(i8),
  Lt_I8(i8),
  LessOrEq_I8(i8),
  OneOf_I8(i8),
  NotOneOf_I8(i8),
  Eq_I8(i8),
  NotEq_I8(i8),
  Between_I8(i8, i8),
  Gt_U16(u16),
  GreaterOrEq_U16(u16),
  Lt_U16(u16),
  LessOrEq_U16(u16),
  OneOf_U16(u16),
  NotOneOf_U16(u16),
  Eq_U16(u16),
  NotEq_U16(u16),
  Between_U16(u16, u16),
  Gt_I16(i16),
  GreaterOrEq_I16(i16),
  Lt_I16(i16),
  LessOrEq_I16(i16),
  OneOf_I16(i16),
  NotOneOf_I16(i16),
  Eq_I16(i16),
  NotEq_I16(i16),
  Between_I16(i16, i16),
  Gt_U32(u32),
  GreaterOrEq_U32(u32),
  Lt_U32(u32),
  LessOrEq_U32(u32),
  OneOf_U32(u32),
  NotOneOf_U32(u32),
  Eq_U32(u32),
  NotEq_U32(u32),
  Between_U32(u32, u32),
  Gt_I32(i32),
  GreaterOrEq_I32(i32),
  Lt_I32(i32),
  LessOrEq_I32(i32),
  OneOf_I32(i32),
  NotOneOf_I32(i32),
  Eq_I32(i32),
  NotEq_I32(i32),
  Between_I32(i32, i32),
  Gt_U64(u64),
  GreaterOrEq_U64(u64),
  Lt_U64(u64),
  LessOrEq_U64(u64),
  OneOf_U64(u64),
  NotOneOf_U64(u64),
  Eq_U64(u64),
  NotEq_U64(u64),
  Between_U64(u64, u64),
  Gt_I64(i64),
  GreaterOrEq_I64(i64),
  Lt_I64(i64),
  LessOrEq_I64(i64),
  OneOf_I64(i64),
  NotOneOf_I64(i64),
  Eq_I64(i64),
  NotEq_I64(i64),
  Between_I64(i64, i64),
  Gt_STRING(String),
  GreaterOrEq_STRING(String),
  Lt_STRING(String),
  LessOrEq_STRING(String),
  OneOf_STRING(String),
  NotOneOf_STRING(String),
  Eq_STRING(String),
  NotEq_STRING(String),
  Between_STRING(String, String),
  Gt_CHAR(char),
  GreaterOrEq_CHAR(char),
  Lt_CHAR(char),
  LessOrEq_CHAR(char),
  OneOf_CHAR(char),
  NotOneOf_CHAR(char),
  Eq_CHAR(char),
  NotEq_CHAR(char),
  Between_CHAR(char, char),
  Gt_Vec_u8(Vec<u8>),
  GreaterOrEq_Vec_u8(Vec<u8>),
  Lt_Vec_u8(Vec<u8>),
  LessOrEq_Vec_u8(Vec<u8>),
  OneOf_Vec_u8(Vec<u8>),
  NotOneOf_Vec_u8(Vec<u8>),
  Eq_Vec_u8(Vec<u8>),
  NotEq_Vec_u8(Vec<u8>),
  Between_Vec_u8(Vec<u8>, Vec<u8>),
  Gt_Vec_String(Vec<String>),
  GreaterOrEq_Vec_String(Vec<String>),
  Lt_Vec_String(Vec<String>),
  LessOrEq_Vec_String(Vec<String>),
  OneOf_Vec_String(Vec<String>),
  NotOneOf_Vec_String(Vec<String>),
  Eq_Vec_String(Vec<String>),
  NotEq_Vec_String(Vec<String>),
  Between_Vec_String(Vec<String>, Vec<String>),
}